"""Add is_active column to interns

Revision ID: 83970f3d2ba8
Revises: 848e5673bec7
Create Date: 2026-06-24 18:07:29.900387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "83970f3d2ba8"
down_revision: Union[str, Sequence[str], None] = "848e5673bec7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "document_id",
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "document_name",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            nullable=False,
            existing_server_default=sa.text("'Pendente'"),
        )
        batch_op.alter_column(
            "feedback",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "last_update",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
            existing_server_default=sa.text(
                "(strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime'))"
            ),
        )

    with op.batch_alter_table("evaluation_criteria", schema=None) as batch_op:
        batch_op.alter_column(
            "criteria_id",
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "name", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "weight",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            nullable=False,
            existing_server_default=sa.text("(1.0)"),
        )
        batch_op.alter_column(
            "last_update",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
            existing_server_default=sa.text("(datetime('now', 'localtime'))"),
        )

    with op.batch_alter_table("grades", schema=None) as batch_op:
        batch_op.alter_column(
            "grade_id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "value", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False
        )
        batch_op.alter_column(
            "last_update",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
            existing_server_default=sa.text("(datetime('now', 'localtime'))"),
        )
        batch_op.create_unique_constraint(
            "uq_intern_criteria", ["intern_id", "criteria_id"]
        )

    with op.batch_alter_table("interns", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False)
        )
        batch_op.alter_column(
            "intern_id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "name", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
        )
        batch_op.alter_column(
            "registration_number",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "email", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "start_date",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "end_date",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "working_days",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "working_hours",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "term", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
        )
        batch_op.alter_column(
            "last_update",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
            existing_server_default=sa.text(
                "(strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime'))"
            ),
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_interns_registration_number"), ["registration_number"]
        )

    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.alter_column(
            "meeting_id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "meeting_date",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_intern_present",
            existing_type=sa.INTEGER(),
            type_=sa.Boolean(),
            existing_nullable=False,
        )

    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.alter_column(
            "observation_id",
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "observation",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "last_update",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
            existing_server_default=sa.text(
                "(strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime'))"
            ),
        )

    with op.batch_alter_table("venues", schema=None) as batch_op:
        batch_op.alter_column(
            "venue_id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "venue_name",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "address",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "supervisor_name",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "supervisor_email",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "supervisor_phone",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "last_update",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
            existing_server_default=sa.text(
                "(strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime'))"
            ),
        )

    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.alter_column(
            "visit_id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "visit_date",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "observation",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "photo_path",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.alter_column(
            "photo_path",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "observation",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "visit_date",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "visit_id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("venues", schema=None) as batch_op:
        batch_op.alter_column(
            "last_update",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text(
                "(strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime'))"
            ),
        )
        batch_op.alter_column(
            "supervisor_phone",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "supervisor_email",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "supervisor_name",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "address",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "venue_name",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "venue_id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.alter_column(
            "last_update",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text(
                "(strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime'))"
            ),
        )
        batch_op.alter_column(
            "observation",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "observation_id",
            existing_type=sa.INTEGER(),
            nullable=True,
            autoincrement=True,
        )

    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.alter_column(
            "is_intern_present",
            existing_type=sa.Boolean(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "meeting_date",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "meeting_id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("interns", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_interns_registration_number"), type_="unique"
        )
        batch_op.alter_column(
            "last_update",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text(
                "(strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime'))"
            ),
        )
        batch_op.alter_column(
            "term", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "working_hours",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "working_days",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "end_date",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "start_date",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "email", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "registration_number",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "name", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "intern_id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )
        batch_op.drop_column("is_active")

    with op.batch_alter_table("grades", schema=None) as batch_op:
        batch_op.drop_constraint("uq_intern_criteria", type_="unique")
        batch_op.alter_column(
            "last_update",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text("(datetime('now', 'localtime'))"),
        )
        batch_op.alter_column(
            "value", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=False
        )
        batch_op.alter_column(
            "grade_id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("evaluation_criteria", schema=None) as batch_op:
        batch_op.alter_column(
            "last_update",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text("(datetime('now', 'localtime'))"),
        )
        batch_op.alter_column(
            "weight",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            nullable=True,
            existing_server_default=sa.text("(1.0)"),
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "name", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "criteria_id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "last_update",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text(
                "(strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime'))"
            ),
        )
        batch_op.alter_column(
            "feedback",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("'Pendente'"),
        )
        batch_op.alter_column(
            "document_name",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "document_id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    # ### end Alembic commands ###
