"""Initial migration

Revision ID: 99ba672f4663
Revises: 4272c1e764d3
Create Date: 2026-03-08 17:07:47.636295

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "99ba672f4663"
down_revision: Union[str, Sequence[str], None] = "4272c1e764d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
